name: current_location
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^12.0.0
  http: ^1.2.1
  google_maps_flutter: ^2.6.1  
  i18n_extension: ^6.0.0 


  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2  

  flutter_lints: ^3.0.0


flutter:
  assets:
    - assets/icons/
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"


